### PR TITLE
RHEL Version

### PR DESCRIPTION
**Pull request by emanuelr93**
I want to add to your repository, springboot-maven-rhel version.

### CODE REVIEW

**Comment by emanuelr93** [comment]
Your CI system don't support RHEL image because it is missing RHEL subscription

**Comment by britter** [comment]
I won't merge this because:

- it just replaces cent-os with RHEL
- it doesn't come with working CI

If you need RHEL support you need to modify the build so that it produces two variants of this image. Furthermore there needs to be a solution for CI.

**Comment by emanuelr93** [comment]
You can use another branch for RHEL. Or you suggest another solutions?

**Comment by britter** [comment]
It is possible to build several images from one branch. Have a look at https://github.com/sclorg/s2i-ruby-container for example.

**Pull request closed without merging**
